multinode: false

modelArtifacts:
  uri: "hf://meta-llama/Llama-3.1-8B"
  name: "meta-llama/Llama-3.1-8B"
  size: 40Gi  # Larger model needs more space
  authSecretName: "llm-d-hf-token"

routing:
  modelName: meta-llama/Llama-3.1-8B
  servicePort: 8000  # Standard port
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      # name: infra-inference-scheduling-inference-gateway # set in helmfile

  proxy:
    image: ghcr.io/llm-d/llm-d-routing-sidecar:v0.2.0
    connector: nixlv2
    secure: false

  inferenceModel:
    create: false

  inferencePool:
    create: false
    # name: gaie-inference-scheduling # set in helmfile

  httpRoute:
    create: false

  epp:
    create: false

decode:
  create: true
  replicas: 1
  monitoring:
    podmonitor:
      enabled: false
      portName: "metrics"
      path: "/metrics"
      interval: "30s"
  containers:
  - name: "vllm"
    image: "ghcr.io/llm-d/llm-d:v0.2.0"
    modelCommand: vllmServe
    args:
      - "--enforce-eager"
      - "--kv-transfer-config"
      - '{"kv_connector":"NixlConnector", "kv_role":"kv_both"}'
      - "--gpu-memory-utilization"
      - "0.85"
    env:
      - name: CUDA_VISIBLE_DEVICES
        value: "0"  # Use first GPU
      - name: UCX_TLS
        value: "cuda_ipc,cuda_copy,tcp"
      - name: VLLM_NIXL_SIDE_CHANNEL_HOST
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: VLLM_NIXL_SIDE_CHANNEL_PORT
        value: "5557"  # Standard port
      - name: VLLM_LOGGING_LEVEL
        value: DEBUG
    ports:
      - containerPort: 5557
        protocol: TCP
      - containerPort: 8200  # Standard metrics port
        name: metrics
        protocol: TCP
    resources:
      limits:
        nvidia.com/gpu: "1"
      requests:
        nvidia.com/gpu: "1"
    mountModelVolume: true
    volumeMounts:
    - name: metrics-volume
      mountPath: /.config
    - name: torch-compile-cache
      mountPath: /.cache
  volumes:
  - name: metrics-volume
    emptyDir: {}
  - name: torch-compile-cache
    emptyDir: {}

prefill:
  create: false
